name: Publish SymCC Docker image
# for testing only
on: [pull_request, workflow_dispatch]
# we want to push a docker image when the  Compile and test SymCC
# workflow completed successfully
# on:
#   workflow_run:
#     workflows: [Compile and test SymCC] # Reuse the name of your tests workflow
#     branches: master
#     types:
#       - completed

jobs:
  upload_dockerhub:
    # if: github.repository == 'eurecom-s3/symcc' && github.ref == 'refs/heads/master'
    # not when testing
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [ llvm_compatibility, llvm_compatibility_latest_llvm ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/symcc:latest
